# Generated by Django 4.2.13 on 2024-07-10 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="email",
        ),
    ]
